insert INTO `course` VALUES (null, '程序设计基础',null);
insert INTO `course` VALUES (null, '高等数学',null);
insert INTO `course` VALUES (null, '线性代数',null);
insert INTO `course` VALUES (null, '离散数学',null);
insert INTO `course` VALUES (null, '概率论与数理统计',null);
insert INTO `course` VALUES (null, '面向对象程序设计',null);
insert INTO `course` VALUES (null, '数据结构',null);
insert INTO `course` VALUES (null, '操作系统',null);
insert INTO `course` VALUES (null, '计算机组成原理',null);
insert INTO `course` VALUES (null, '计算机导论',null);
-- INSERT INTO `course` VALUES (null, '计算机网络',null);
-- INSERT INTO `course` VALUES (null, '软件工程',null);
-- INSERT INTO `course` VALUES (null, '软件测试方法和技术',null);
-- INSERT INTO `course` VALUES (null, '移动终端编程',null);
-- INSERT INTO `course` VALUES (null, 'WEB初级编程',null);
-- INSERT INTO `course` VALUES (null, 'WEB高级编程',null);
-- INSERT INTO `course` VALUES (null, '军事理论',null);
-- INSERT INTO `course` VALUES (null, '职业生涯规划',null);
-- INSERT INTO `course` VALUES (null, '心理健康教育',null);
-- INSERT INTO `course` VALUES (null, '中国近代史纲要',null);
-- INSERT INTO `course` VALUES (null, '毛泽东思想和中国特色社会主义理论体系概论',null);
-- INSERT INTO `course` VALUES (null, 'Linux基础',null);
--
insert INTO `major` VALUES (null, '软件工程',null);
insert INTO `major` VALUES (null, '物联网工程',null);
insert INTO `major` VALUES (null, '数据科学与大数据技术',null);
insert INTO `major` VALUES (null, '通信工程',null);
insert INTO `major` VALUES (null, '网络工程',null);
insert INTO `major` VALUES (null, '无机非金属材料工程',null);
insert INTO `major` VALUES (null, '计算机科学与技术',null);
insert INTO `major` VALUES (null, '金属材料工程',null);
insert INTO `major` VALUES (null, '高分子材料工程',null);
insert INTO `major` VALUES (null, '复合材料工程',null);
insert INTO `major` VALUES (null, '应用化学',null);
-- INSERT INTO `major` VALUES (null, '材料化学',null);
-- INSERT INTO `major` VALUES (null, '电气工程及其自动化',null);
-- INSERT INTO `major` VALUES (null, '飞行器设计与工程',null);
-- INSERT INTO `major` VALUES (null, '飞行器制造工程',null);
-- INSERT INTO `major` VALUES (null, '焊接技术与工程',null);
-- INSERT INTO `major` VALUES (null, '信息与计算科学',null);
-- INSERT INTO `major` VALUES (null, '数学与应用数学',null);
-- INSERT INTO `major` VALUES (null, '光电信息科学与工程',null);
-- INSERT INTO `major` VALUES (null, '生物医学工程',null);
-- INSERT INTO `major` VALUES (null, '经济学',null);
-- INSERT INTO `major` VALUES (null, '工商管理',null);
-- INSERT INTO `major` VALUES (null, '会计学',null);
-- INSERT INTO `major` VALUES (null, '电子商务',null);
-- INSERT INTO `major` VALUES (null, '土木工程',null);
-- INSERT INTO `major` VALUES (null, '交通工程',null);
-- INSERT INTO `major` VALUES (null, '工业设计',null);
-- INSERT INTO `major` VALUES (null, '动画',null);
-- INSERT INTO `major` VALUES (null, '视觉传达设计',null);
-- INSERT INTO `major` VALUES (null, '环境设计',null);
-- INSERT INTO `major` VALUES (null, '服装与服饰设计',null);
-- INSERT INTO `major` VALUES (null, '法学',null);
-- INSERT INTO `major` VALUES (null, '新闻学',null);
-- INSERT INTO `major` VALUES (null, '播音与主持艺术',null);
-- INSERT INTO `major` VALUES (null, '音乐学',null);
-- INSERT INTO `major` VALUES (null, '舞蹈学',null);
-- INSERT INTO `major` VALUES (null, '表演',null);
-- INSERT INTO `major` VALUES (null, '英语',null);
-- INSERT INTO `major` VALUES (null, '电子信息工程',null);
--
insert INTO `school` VALUES (null, '清华大学', null, null,null);
insert INTO `school` VALUES (null, '北京大学', null, null,null);
insert INTO `school` VALUES (null, '中国人民大学', null, null,null);
insert INTO `school` VALUES (null, '上海大学', null, null,null);
insert INTO `school` VALUES (null, '上海第二工业大学', null, null,null);
insert INTO `school` VALUES (null, '上海轻工业大学', null, null,null);
insert INTO `school` VALUES (null, '上海应用技术大学', null, null,null);
insert INTO `school` VALUES (null, '南昌大学', null, null,null);
insert INTO `school` VALUES (null, '南昌航空大学', '丰和南大道696号', 'null',null);
-- INSERT INTO `school` VALUES (null, '江西财经大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '华东交通大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '九江学院', null, null,null);
-- INSERT INTO `school` VALUES (null, '华南理工大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '广州大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '中山大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '深圳大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '武汉大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '南京大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '河海大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '郑州大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '河南大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '河南理工大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '河南科技大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '南阳理工大学', null, null,null);
-- INSERT INTO `school` VALUES (null, '濮阳工学院', null, null,null);

insert INTO `user` VALUES (null, 'NISHIKINOWuzhu', '321321', 'Man', '516942590@qq.com', '18079148395');
insert INTO `user` VALUES (null, 'wuzhu', '123123' , 'Woman', '2927962422@qq.com', '13839377962');

insert INTO `book` VALUES (null, 'Android移动应用开发教程', '清华大学出版社', '978-7-302-49105-7', '祝永志', '', 49, 'TJ', 'Admin', 0, 'images/default.png',0);
insert INTO `book` VALUES (null, '软件测试方法和技术', '清华大学出版社', '978-7-302-37031-4', '朱少民', '', 44.5, 'TJ', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'qwe', '清华大学出版社', '978-7-302-37031-4', '朱少民', '', 44.5, 'TJ', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'asd', '清华大学出版社', '978-7-302-37031-5', '朱多民', '', 44.5, 'TW', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'zxc', '清华大学出版社', '978-7-302-37031-6', '朱巨民', '', 44.5, 'TE', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'rty', '清华大学出版社', '978-7-302-37031-7', '羊少民', '', 44.5, 'TR', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'fgh', '清华大学出版社', '978-7-302-37031-8', '牛少民', '', 44.5, 'TT', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'vbn', '清华大学出版社', '978-7-302-37031-9', '朱少皇', '', 44.5, 'TY', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'uio', '清华大学出版社', '978-7-302-37031-0', '朱少少', '', 44.5, 'TU', 'Admin', 0, 'images/20191231170610.png',0);
insert INTO `book` VALUES (null, 'jkl', '清华大学出版社', '978-7-302-37031-1', '朱猪猪', '', 44.5, 'TI', 'Admin', 0, 'images/20191231170610.png',0);
