DELETE https://localhost:8080/api/v1/schoolMajors/delete?school_id=5&major_id=6
Content-Type: application/json


###
POST https://localhost:8080/api/v1/schoolMajors/insert
Content-Type: application/json

{
  "school_id": 5,
  "major_id": 6
}

###
GET https://localhost:8080/api/v1/schoolMajors/1
Accept: application/json

###
